name: Tests navig
on: [ workflow_call ]

concurrency:
  group: tests-navig-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: 'bash'

jobs:
  tests_navig:
    strategy:
      fail-fast: false
      matrix:
        navig: [ firefox, chromium] #  , webkit ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - uses: pnpm/action-setup@v4.1.0
        with:
          version: latest

      - uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
      - run: pnpm install

      - run: pnpm exec playwright install

      - run: pnpm test:webkit
        if: ${{ matrix.navig == 'webkit' }}

      - run: pnpm test:chrome
        if: ${{ matrix.navig == 'chromium' }}

      - run: pnpm test:firefox
        if: ${{ matrix.navig == 'firefox' }}

      # Publier couverture tests
      - name: Envoyer couverure à Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

