name: Appli installable
on: [ workflow_call ]

concurrency:
  group: tests-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: 'bash'

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest, ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - uses: pnpm/action-setup@v4.1.0
        with:
          version: latest

      - uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
      - run: pnpm install
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
      - run: pnpm test:main
      - run: pnpm test:preload
      - run: pnpm test:renderer

      # De https://github.com/microsoft/playwright/issues/34251
      - run: sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0
        if: contains(matrix.os, 'ubuntu')


      # I ran into problems trying to run an electron window in ubuntu due to a missing graphics server.
      # That's why this special command for Ubuntu is here
      - run: xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- pnpm test:e2e
        if: contains(matrix.os, 'ubuntu')

      - run: pnpm test:e2e
        if: "!contains(matrix.os, 'ubuntu')"

      # Publier couverture tests
      - name: Envoyer couverure à Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
